/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gameframe.java
 *
 * Created on Nov 29, 2011, 2:36:35 PM
 */
package View;

import Components.GameState;
import Components.Logger;
import Model.Game;
import java.awt.BorderLayout;

/**
 *
 * @author Laurens
 */
public class Gameframe extends javax.swing.JFrame {

	private Game game;
	/** Creates new form Gameframe */
	public Gameframe() {
		initComponents();
		jPlayfieldPanel.setLayout(new BorderLayout());
		Logger.log("Gameframe loaded.");
        game = new Game(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlayfieldPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jItemStart = new javax.swing.JMenuItem();
        jItemPause = new javax.swing.JMenuItem();
        jItemStop = new javax.swing.JMenuItem();
        jItemReset = new javax.swing.JMenuItem();
        jItemOptions = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(null);

        jPlayfieldPanel.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPlayfieldPanelLayout = new javax.swing.GroupLayout(jPlayfieldPanel);
        jPlayfieldPanel.setLayout(jPlayfieldPanelLayout);
        jPlayfieldPanelLayout.setHorizontalGroup(
            jPlayfieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        jPlayfieldPanelLayout.setVerticalGroup(
            jPlayfieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jMenu1.setText("Game");

        jItemStart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jItemStart.setText("Start");
        jItemStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemStartActionPerformed(evt);
            }
        });
        jMenu1.add(jItemStart);

        jItemPause.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jItemPause.setText("Pause");
        jItemPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemPauseActionPerformed(evt);
            }
        });
        jMenu1.add(jItemPause);

        jItemStop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jItemStop.setText("Stop");
        jItemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemStopActionPerformed(evt);
            }
        });
        jMenu1.add(jItemStop);

        jItemReset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jItemReset.setText("Reset");
        jItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemResetActionPerformed(evt);
            }
        });
        jMenu1.add(jItemReset);

        jItemOptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jItemOptions.setText("Options");
        jItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemOptionsActionPerformed(evt);
            }
        });
        jMenu1.add(jItemOptions);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPlayfieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPlayfieldPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jItemStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemStartActionPerformed
		game.start();
	}//GEN-LAST:event_jItemStartActionPerformed

	private void jItemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemStopActionPerformed
		game.stop();
	}//GEN-LAST:event_jItemStopActionPerformed

	private void jItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemResetActionPerformed
		game.reset();
	}//GEN-LAST:event_jItemResetActionPerformed

	private void jItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemOptionsActionPerformed
		game.pause();
		game.showOptionsPanel();
	}//GEN-LAST:event_jItemOptionsActionPerformed

	private void jItemPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemPauseActionPerformed
		if (game.getGameState() == GameState.PAUSED) {
			game.start();
			jItemPause.setText("Pause");
		} else {
			game.pause();
			jItemPause.setText("Resume");
		}		
	}//GEN-LAST:event_jItemPauseActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Gameframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Gameframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Gameframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Gameframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Gameframe().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemOptions;
    private javax.swing.JMenuItem jItemPause;
    private javax.swing.JMenuItem jItemReset;
    private javax.swing.JMenuItem jItemStart;
    private javax.swing.JMenuItem jItemStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPlayfieldPanel;
    // End of variables declaration//GEN-END:variables
}
