/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * End.java
 *
 * Created on Dec 20, 2011, 2:56:36 PM
 */
package View;

import Components.GameState;
import Model.Game;

/**
 *
 * @author Laurens
 */
public class StatusPanel extends javax.swing.JPanel {

	private Game game;
	/** Creates new form End */
	public StatusPanel(Game game) {
		initComponents();
		this.game = game;
		initText();
	}
	
	private void initText() {
		switch (game.getState()) {
			case LOST:
				lblText.setText("FAILURE!");
				lblF3.setVisible(false);
				break;
			case WON:
				lblText.setText("VICTORY!");
				lblF3.setVisible(false);
				break;
			case PAUSED:
				lblText.setText("Game paused");
				break;
			case STOPPED:
				lblText.setText("Game stopped");
				lblF3.setVisible(false);
				break;				
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        lblF3 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblF10 = new javax.swing.JLabel();
        lblF11 = new javax.swing.JLabel();

        lblText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblF3.setText("Press \"F3\" to resume playing");

        lblF5.setText("Press \"F5\" to start a new game");

        lblF4.setText("Press \"F4\" to stop playing");

        lblF10.setText("Press \"F10\" to go to the option menu");

        lblF11.setText("Press \"F11\" to view the highscores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblF5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblF3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lblF4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblF10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblF11, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblF3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblF5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblF4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblF10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblF11)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblF10;
    private javax.swing.JLabel lblF11;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
